package it.monaco.medical.service.model.enums;

public enum ErrorCode {

    //quattrruote
    QTR_001_MISSING_INPUTS("QUATTRORUOTE-001"),
    QTR_002_INVALID_INPUTS("QUATTRORUOTE-002"),
    QTR_003_VEHICLE_MAKERS_NOT_FOUND("QUATTRORUOTE-003"),
    QTR_004_VEHICLE_MAKERS_DATABASE_ERROR("QUATTRORUOTE-004"),
    QTR_005_VEHICLE_MODEL_NOT_FOUND("QUATTRORUOTE-005"),
    QTR_006_VEHICLE_MODEL_DATABASE_ERROR("QUATTRORUOTE-006"),
    QTR_007_VEHICLE_SUPPLIES_NOT_FOUND("QUATTRORUOTE-007"),
    QTR_008_VEHICLE_SUPPLIES_DATABASE_ERROR("QUATTRORUOTE-008"),
    QTR_009_VEHICLE_DATA_OPTIONAL_NOT_FOUND("QUATTRORUOTE-009"),
    QTR_010_VEHICLE_DATA_OPTIONAL_DATABASE_ERROR("QUATTRORUOTE-010"),
    QTR_011_VEHICLE_SETUP_NOT_FOUND("QUATTRORUOTE-011"),
    QTR_012_VEHICLE_SETUP_DATABASE_ERROR("QUATTRORUOTE-012"),
    QTR_013_VEHICLE_NOT_FOUND("QUATTRORUOTE-013"),
    QTR_014_VEHICLE_DATABASE_ERROR("QUATTRORUOTE-014"),
    QTR_994_VEHICLE_UNEXPECTED_ERROR("QUATTRORUOTE-994"),
    QTR_995_VEHICLE_DATA_OPTIONAL_UNEXPECTED_ERROR("QUATTRORUOTE-995"),
    QTR_996_VEHICLE_SETUP_UNEXPECTED_ERROR("QUATTRORUOTE-996"),
    QTR_997_VEHICLE_SUPPLIES_UNEXPECTED_ERROR("QUATTRORUOTE-997"),
    QTR_998_VEHICLE_MODELS_UNEXPECTED_ERROR("QUATTRORUOTE-998"),
    QTR_999_VEHICLE_MAKERS_UNEXPECTED_ERROR("QUATTRORUOTE-999"),

    // quattroruote generic
    LEG_999_UNEXPECTED_ERROR("LEG_999");


    private String code;

    ErrorCode(String code)
    {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
